import { Colors } from "@/constand/colors";
import { StyleSheet, TextInput } from "react-native";

export const styles = StyleSheet.create({
  container: {
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  title: {
    fontSize: 24,
    fontWeight: 800,
    textAlign: "center",
    marginBottom: 6,
    color: Colors.secondary,
  },
  subtitle: {
    fontSize: 16,
    textAlign: "center",
    color: "rgba(0,0,0,0.6)",
  },
  card: {
    backgroundColor: Colors.primary,
    borderRadius: 12,
    padding: 24,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  cardText: {
    color: Colors.white,
    fontSize: 16,
    marginBottom: 8,
  },
  cardTotal: {
    color: Colors.white,
    fontSize: 24,
    fontWeight: 800,
  },
  filterButton: {
    backgroundColor: Colors.gray,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 16,
    marginRight: 8,
    marginBottom: 8,
  },
  activeFilter: {
    backgroundColor: Colors.secondary,
  },
  activeFilterText: {
    color: Colors.white,
    fontWeight: 600,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 600,
    color: Colors.secondary,
    marginVertical: 12,
  },
  filterContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  datePickerButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ccc",
    gap: 6,
  },
  clearButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: Colors.gray,
  },
  expenseItem: {
    backgroundColor: Colors.white,
    padding: 12,
    borderRadius: 12,
    shadowColor: "#000",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: Colors.primary,
  },
  expenseTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: Colors.secondary,
  },
  expenseCategory: {
    fontSize: 14,
    color: Colors.gray,
  },
  expenseAmount: {
    fontSize: 16,
    fontWeight: 600,
    color: Colors.secondary,
  },
  inputTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: Colors.secondary,
    marginBottom: 6,
  },
  inputText: {
    fontSize: 16,
    borderWidth: 1,
    borderColor: Colors.gray,
    borderRadius: 8,
    padding: 10,
    paddingVertical: 12,
    paddingLeft: 12,
    marginBottom: 10,
  },
  categoryTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: Colors.secondary,
    marginBottom: 6,
  },
  addButton: {
    backgroundColor: Colors.primary,
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  addButtonText: {
    color: Colors.white,
    fontWeight: 600,
    fontSize: 16,
  },
  aboutTitle: {
    fontSize: 20,
    fontWeight: 800,
    color: Colors.primary,
  },
  aboutText: {
    fontSize: 16,
    color: Colors.secondary,
    marginTop: 4,
  },
});
